### ISSUE TITLE
How to get the final results?

### ISSUE THREAD

**Issue by MMahdi97** [premise-community-scenarios/hydrogen-prospective-scenarios#1]
Hello everyone,

I tried to run this example, but I have some questions.
First of all, when I use this code `ndb.update_external_scenario()` I have the following error 
![image](https://github.com/premise-community-scenarios/hydrogen-prospective-scenarios/assets/170021288/c26e4763-dfd9-4ce1-b5bc-b5478b62bf4b)

Moreover, I don't know how to export the results as it is called **"scenario_diff_Hydrogen-REMIND-2023-1214.xlsx"**
Could someone please help me?

Thank you so much

**Comment by romainsacchi** [comment]
Hi @MMahdi97 , sorry I just saw this now. Starting `v.2.0.0`, you need to use `.update()` (e.g., `.update("external")` for external scenarios).

**Comment by romainsacchi** [comment]
I updated the example so that future users do not replicate this.

**Comment by romainsacchi** [comment]
Regarding your second question, `premise` prints the file path where to find the Excel file.
